  deploy:
    runs-on: ubuntu-latest
    needs: [build_backend, build_frontend, build_gateway]
    steps:
    - uses: actions/checkout@v3
    - name: Copy compose file
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.SSH_KEY }}
        source: "docker-compose.production.yml"
        target: "kittygram"
    - name: Copy env file
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.SSH_KEY }}
        source: ".env"
        target: "kittygram"
        - name: Deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          cd kittygram
          
          echo "POSTGRES_USER=kittygram_user" > .env
          echo "POSTGRES_PASSWORD=kittygram_password" >> .env
          echo "POSTGRES_DB=kittygram" >> .env
          echo "DB_HOST=db" >> .env
          echo "DB_PORT=5432" >> .env
          sudo docker compose -f docker-compose.production.yml pull
          sudo docker compose -f docker-compose.production.yml down
          sudo docker compose -f docker-compose.production.yml up -d
          sudo docker compose -f docker-compose.production.yml exec backend python manage.py migrate
          sudo docker compose -f docker-compose.production.yml exec backend python manage.py collectstatic --noinput
          sudo docker compose -f docker-compose.production.yml exec backend cp -r /app/collected_static/. /static_backend/static/